name: AnalogClocks
main: me.jascotty2.analogclock.AnalogClocks
version: 1.1
api-version: 1.13
website: http://github.com/jascotty2
author: jascotty2
description: Physical clock face for minecraft
softdepend: [WorldEdit]
commands:
  analogclock:
    description: AnalogClock
    usage: |
      /analogclock create <name> [hour-block] [minute-block] [center-block] [hours-only]
      /analogclock delete <name>
      /analogclock list
    permission: analogclock.admin
permissions:
  analogclock.admin:
    default: op